<!DOCTYPE html>
<html>

<head>
    <title>Task Force List Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        h1 {
            font-size: 18px;
            margin-bottom: 5px;
        }

        .meta {
            color: #666;
            font-size: 10px;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>
    <h1>Task Force Master List</h1>
    <div class="meta">Generated by TFMS on {{ now()->toDateTimeString() }}</div>

    <table>
        <thead>
            <tr>
                <th>Task Force Name</th>
                <th>Leader</th>
                <th>Department(s)</th>
                <th>Members</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $tf)
                <tr>
                    <td>{{ $tf->name }}</td>
                    <td>{{ $tf->leader->name ?? 'N/A' }}</td>
                    <td>{{ $tf->departments->pluck('name')->join(', ') }}</td>
                    <td>{{ $tf->members->count() }}</td>
                    <td>
                        {{ $tf->is_locked ? 'Locked' : 'Unlocked' }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>