<?php

namespace App\Policies;

use App\Models\Report;
use App\Models\User;
use App\Models\Staff;

class ReportPolicy
{
    /**
     * Determine whether the user can view any models.
     */
    public function viewAny(User $user): bool
    {
        return true; // Filtering happens in controller
    }

    /**
     * Determine whether the user can view the model.
     */
    public function view(User $user, Report $report): bool
    {
        if ($user->isAdmin() || $user->isPSM()) {
            return true;
        }

        if ($user->isHOD()) {
            // Can view reports for their department
            if ($report->department_id && $user->department_id === $report->department_id) {
                return true;
            }
            // Can view reports for staff in their department
            if ($report->staff_id && $report->staff && $report->staff->department_id === $user->department_id) {
                return true;
            }
        }

        // Can view own reports (generated by me or about me)
        if ($report->generated_by === $user->id) {
            return true;
        }
        if ($report->staff_id && $report->staff_id === $user->id) {
            return true;
        }

        return false;
    }

    /**
     * Determine whether the user can create models.
     */
    public function create(User $user): bool
    {
        return $user->isAdmin() || $user->isPSM() || $user->isHOD() || $user->isLecturer();
    }

    /**
     * Determine whether the user can delete the model.
     */
    public function delete(User $user, Report $report): bool
    {
        return $user->isAdmin();
    }
}
