<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Models\AuditLog;

use App\Services\WorkloadService; // Add import

class DashboardController extends Controller
{
    public function index(WorkloadService $workloadService)
    {
        $user = Auth::user();

        if ($user->isAdmin()) {
            $recentLogs = AuditLog::with('user')->latest()->take(5)->get();

            // System Health Metrics

            // 1. Storage Usage (Disk Free Space)
            $diskTotal = disk_total_space(base_path());
            $diskFree = disk_free_space(base_path());
            $diskUsed = $diskTotal - $diskFree;
            $storageUsage = round(($diskUsed / $diskTotal) * 100);

            // 2. Database Size (Estimated)
            $dbSize = 0;
            $dbConnection = config('database.default');
            if ($dbConnection === 'sqlite') {
                $dbPath = config('database.connections.sqlite.database');
                if (file_exists($dbPath)) {
                    $dbSize = filesize($dbPath);
                }
            } elseif ($dbConnection === 'mysql') {
                try {
                    $dbName = config('database.connections.mysql.database');
                    $result = DB::select('SELECT SUM(data_length + index_length) AS size FROM information_schema.TABLES WHERE table_schema = ?', [$dbName]);
                    $dbSize = $result[0]->size ?? 0;
                } catch (\Exception $e) {
                    $dbSize = 0;
                }
            }
            // Assume 100MB quota for visualization
            $dbQuota = 100 * 1024 * 1024;
            $dbLoad = round(($dbSize / $dbQuota) * 100);
            if ($dbLoad > 100)
                $dbLoad = 100;

            // 3. Memory Usage (PHP Memory Limit)
            $memoryLimit = ini_get('memory_limit');
            if (preg_match('/^(\d+)(.)$/', $memoryLimit, $matches)) {
                if ($matches[2] == 'M') {
                    $memoryLimitBytes = $matches[1] * 1024 * 1024;
                } elseif ($matches[2] == 'K') {
                    $memoryLimitBytes = $matches[1] * 1024;
                } elseif ($matches[2] == 'G') {
                    $memoryLimitBytes = $matches[1] * 1024 * 1024 * 1024;
                } else {
                    $memoryLimitBytes = 128 * 1024 * 1024; // Default fallback
                }
            } else {
                $memoryLimitBytes = 128 * 1024 * 1024;
            }
            $memoryUsed = memory_get_usage(true);
            $memoryUsage = round(($memoryUsed / $memoryLimitBytes) * 100);
            // Ensure it shows at least something visible
            if ($memoryUsage < 5)
                $memoryUsage = 5;

            return view('dashboard.admin', compact('recentLogs', 'storageUsage', 'dbLoad', 'memoryUsage'));
        } elseif ($user->isHOD()) {
            return view('dashboard.hod');
        } elseif ($user->isPSM()) {
            return view('dashboard.psm');
        } elseif ($user->isLecturer()) {
            // Calculate Dashboard Data
            $totalWorkload = $user->calculateTotalWorkload();
            $status = $workloadService->calculateStatus($totalWorkload);
            $statusColor = $workloadService->getStatusColor($status);
            $activeTasksCount = $user->taskForces()->where('active', true)->count();
            // Thresholds for progress bar context if needed (optional)
            $maxWeightage = (float) (\App\Models\Configuration::where('config_key', 'max_weightage')->value('config_value') ?? 20);


            return view('dashboard.lecturer', compact('totalWorkload', 'status', 'statusColor', 'activeTasksCount', 'maxWeightage'));
        } elseif ($user->hasRole('management')) {
            // Management Dashboard KPIs
            $totalStaff = \App\Models\User::whereNotNull('department_id')->count();
            $totalDepartments = \App\Models\Department::count();
            $activeTaskForces = \App\Models\TaskForce::where('active', true)->count();

            return view('dashboard.management', compact('totalStaff', 'totalDepartments', 'activeTaskForces'));
        } else {
            return view('layouts.dashboard'); // Fallback
        }
    }

    public function downloadSystemReport()
    {
        $filename = 'system-report-' . date('Y-m-d') . '.txt';
        $content = "TFMS System Health Report\n";
        $content .= "Generated on: " . now()->toDateTimeString() . "\n";
        $content .= "Generated by: " . Auth::user()->name . "\n\n";

        $content .= "--- System Metrics ---\n";
        $content .= "PHP Version: " . phpversion() . "\n";
        $content .= "Laravel Version: " . app()->version() . "\n";
        $content .= "Server OS: " . php_uname() . "\n\n";

        $content .= "--- Database Statistics ---\n";
        $content .= "Users: " . \App\Models\User::count() . "\n";
        $content .= "Staff: " . \App\Models\User::whereNotNull('department_id')->count() . "\n";
        $content .= "Departments: " . \App\Models\Department::count() . "\n";
        $content .= "Task Forces: " . \App\Models\TaskForce::count() . "\n";
        $content .= "Audit Logs: " . \App\Models\AuditLog::count() . "\n\n";

        return response($content)
            ->header('Content-Type', 'text/plain')
            ->header('Content-Disposition', 'attachment; filename="' . $filename . '"');
    }
}
